variables:
  PACKAGE_SCHEME: "MyGuavaPaymentSDK"
  RELEASE_BRANCH: "github-release"
  GH_TARGET_BRANCH: "master"
  TAG_TARGET_SHA: ""
  DEBUG: 0

stages:
  - build
  - test
  - helpers
  - version
  - release

default:
  tags:
    - ios
  before_script:
    - set -euo pipefail
    - xcodebuild -version
    - swift --version
    - "export LC_ALL=en_US.UTF-8"
    - "export LANG=en_US.UTF-8"

cache:
  key: "gems-${CI_COMMIT_REF_SLUG}"
  paths:
    - .gem/

workflow:
  rules:
    # Start pipelines for Merge Request events (creation/updates and pushes to MR source branches)
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    # Start pipelines for pushes to target branches when an MR is merged (i.e., develop or master)
    # NOTE: To ensure only MR merges trigger these, protect branches to disallow direct pushes.
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^(develop|master)$/'
      when: always
    # Allow manual Web-triggered pipelines
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

build_ios:
  stage: build
  when: always
  script:
    - fastlane build_sdk

test_ios:
  stage: test
  needs:
    - build_ios
  when: always
  script:
    - fastlane test_sdk

update_version:
  stage: version
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "develop"'
      when: manual
    - when: never
  before_script:
    - chmod +x ci/update_version.sh
  script:
    - bash ci/update_version.sh

release_branch_update:
  stage: release
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - when: never
  before_script:
    - chmod +x ci/release_branch_update.sh
  script:
    - bash ci/release_branch_update.sh
  tags:
    - ios

publish_release:
  stage: release
  needs:
    - release_branch_update
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  before_script:
    - chmod +x ci/publish_release.sh
  script:
    - bash ci/publish_release.sh
  tags:
    - ios

fix_release_branch:
  stage: helpers
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == $RELEASE_BRANCH)'
      when: manual
    - when: never
  script:
    - git add .
    - git reset --hard
    - git tag -l | xargs git tag -d
    - git checkout -B temp-branch
    - git branch | grep -v "temp-branch" | xargs git branch -D
  tags:
    - ios
